### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by MaxenceMax** [zthxxx/jovial#12]
after installation, I have those errors : 

```
update_terminal_cwd:12: failed to load module `zsh/pcre': dlopen(/usr/lib/zsh/5.7.1/zsh/pcre.so, 9): image not found                                                                                                
update_terminal_cwd:12: -pcre-match not available for regex
regexp-replace:28: failed to load module `zsh/pcre': dlopen(/usr/lib/zsh/5.7.1/zsh/pcre.so, 9): image not found
regexp-replace:28: -pcre-match not available for regex
regexp-replace:28: failed to load module `zsh/pcre': dlopen(/usr/lib/zsh/5.7.1/zsh/pcre.so, 9): image not found
regexp-replace:28: -pcre-match not available for regex
regexp-replace:28: failed to load module `zsh/pcre': dlopen(/usr/lib/zsh/5.7.1/zsh/pcre.so, 9): image not found
regexp-replace:28: -pcre-match not available for regex
regexp-replace:28: failed to load module `zsh/pcre': dlopen(/usr/lib/zsh/5.7.1/zsh/pcre.so, 9): image not found
regexp-replace:28: -pcre-match not available for regex
```

do you have ant idea why ?

**Comment by zthxxx** [comment]
seems like a zsh bug,

try `brew install zsh --with-pcre`

maybe those can help you
- https://github.com/zplug/zplug/issues/457
- https://github.com/ohmyzsh/ohmyzsh/issues/7825#issuecomment-489176660

**Comment by MaxenceMax** [comment]
i already tried it and I have this error :  
```
Error: invalid option: --with-pcre
```

**Comment by zthxxx** [comment]
I found some same questions, and a answer is just install pcre，

maybe you can try `brew install pcre pcre2`

**Comment by Pensu** [comment]
I am also facing the same issue. 

```brew install pcre pcre2``` isn't working either. @MaxenceMax Did you find any solution?

**Comment by zthxxx** [comment]
> I am also facing the same issue.
> 
> `brew install pcre pcre2` isn't working either. @MaxenceMax Did you find any solution?

@Pensu  What's your zsh version? `zsh 5.7.1 (x86_64-apple-darwin18.2.0)` for me

**Comment by Pensu** [comment]
> > I am also facing the same issue.
> > `brew install pcre pcre2` isn't working either. @MaxenceMax Did you find any solution?
> 
> @Pensu What's your zsh version? `zsh 5.7.1 (x86_64-apple-darwin18.2.0)` for me

Hey @zthxxx, mice is `zsh 5.7.1 (x86_64-apple-darwin19.0)`

**Comment by zthxxx** [comment]
@Pensu  maybe try 

```bash
brew uninstall zsh
brew reinstall pcre pcre2
```

to make sure it will `reinstall` pcre module

**Comment by zthxxx** [comment]
@Pensu  

after `brew install zsh`, there are "two zsh",

one is `/usr/local/bin/zsh`, installed by brew, no problem;

and another is `/bin/zsh`, built-in with macOS Catalina, failed to load `pcre.so`.

so you need  `chsh` to `/usr/local/bin/zsh` manually.

![image](https://user-images.githubusercontent.com/15135943/89780452-0bc5e880-db44-11ea-828a-c91da701a211.png)

**Comment by zthxxx** [comment]
@MaxenceMax  see details above

**Comment by MaxenceMax** [comment]
@zthxxx thank you a lot ! it's working like a charm !

**Comment by zthxxx** [comment]
## Summary

built-in with macOS Catalina zsh (`/bin/zsh`), will failed to load pcre.so.

so you need chsh to `/usr/local/bin/zsh` manually, which is install with brew.

```bash
brew install zsh 
sudo chsh -s `command -v zsh` $USER
```
