### ISSUE TITLE
Continued error "bad math expression: illegal character: }" when exec specify command ":(){return 0}}"

### ISSUE THREAD

**Issue by zthxxx** [zthxxx/jovial#14]
specify command `:(){return 0}}`

![image](https://user-images.githubusercontent.com/15135943/116670525-681eb000-a9d2-11eb-8ca1-2d76af44be56.png)

**Comment by ejuarezg** [comment]
I can also reproduce this bug, though I have no clue what's causing it.

**Comment by zthxxx** [comment]
@ejuarezg  that's not a BUG of theme or shell.

It just due to the colon `:` is a builtin command in many shell (like zsh and bash), sometimes used as comments in any time, sometimes used as equivalent to the true command,

```bash
echo ok
: this is a command but do nothing, so we used it like comments
```

However, in this issue, `:(){return 0}}` means override the builtin colon command `:` to bind as an other function with body `return 0}`. Obviously the function body have syntax error and will throw error message when it execute.

Additionally If you have used oh-my-zsh, the colon command `:` also be used in oh-my-zsh scripts In many places, it will exec pre every prompt display;

**Comment by ejuarezg** [comment]
Thanks for the clarification.
