### ISSUE TITLE
Promot change to $(@jovial-prompt) after source theme file.

### ISSUE THREAD

**Issue by 404cn** [zthxxx/jovial#16]
Like title says, I download jovial.zsh-theme and source it, and my shell prompt looks like this:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/24653356/143456068-0e9fa07d-0c4e-44f0-a21c-64790b2c743c.png">

**Comment by zthxxx** [comment]
@404cn  Sorry, also add `setopt prompt_subst` in .zshrc before load(source) theme file

I will add it to README later

**Comment by 404cn** [comment]
@zthxxx  Thanks it works!
