### ISSUE TITLE
@jovial-prompt:1: bad floating point constant after source zshrc file

### ISSUE THREAD

**Issue by 404cn** [zthxxx/jovial#17]
OS: MacOS 12.0.1
Shell: zsh 5.8 (x86_64-apple-darwin21.0)
Terminal: iTerm2 Build 3.4.12

And here is my little zshrc file to reproduce this problem:

```shell
ZPLUGINDIR=$HOME/.zsh/plugins

function load-file () {
    local url="$1"
    local file_name=${${url##*/}%}
    local dir_name="${ZPLUGINDIR:-$HOME/.zsh/plugins}/$file_name"

    if [[ ! -d $dir_name ]]; then
        mkdir -p $dir_name
    fi
    if [[ ! -f $dir_name/$file_name ]]; then
                echo "Downloading $url..."
        curl -sSL $url -o $dir_name/$file_name
    fi

    source $dir_name/$file_name
    fpath+=$dir_name
}

setopt prompt_subst

autoload -U colors && colors

typeset -AHg FG BG

for color in {000..255}; do
  FG[$color]="%{\e[38;5;${color}m%}"
  BG[$color]="%{\e[48;5;${color}m%}"
done

files=(
  https://github.com/zthxxx/jovial/raw/master/jovial.zsh-theme
)

for file in $files; do
    load-file ${file}
done
unset file
```

But it worked if I source theme the theme file `~/.zsh/plugins/jovial.zsh-theme/jovial.zsh-theme` interactively.

I have no idea whats going on 🥵

**Comment by zthxxx** [comment]
@404cn  it's not a problem of `jovial`

DON'T let `source` command in function while you need to load theme file, only use `source` in top-level `for` loop if you need.

That's very different, you can see how it used in oh-my-zsh scripts.

**Comment by 404cn** [comment]
Thanks for your reply.

I will close this issue and try to figure it out since it's not a problem of `jovial`.

**Comment by zthxxx** [comment]
@404cn  The different is function create a "context scope", so local/global variables scope will wrong, but I can compatible with this case 😂

**Comment by zthxxx** [comment]
Compatibility code updated.

**Comment by 404cn** [comment]
> @404cn The different is function create a "context scope", so local/global variables scope will wrong, but I can compatible with this case 😂

https://github.com/mattmc3/zsh_unplugged

Actually I use this in my config file and it works so I try to wrote `load-file`  to download single file and it's not work like before.



> Compatibility code updated.

Yeaaaaaa! It worked after this update, and I don't have to change anything.
