### ISSUE TITLE
sed: 1: "/Users/mac/.zshrc": invalid command code m

### ISSUE THREAD

**Issue by aitbahaa** [zthxxx/jovial#2]
While installing and after typing the command given in the readme file i get this error :

chsh: no changes made
sed: 1: "/Users/mac/.zshrc": invalid command code m
sed: 1: "/Users/mac/.zshrc": invalid command code m
Warning: git 2.20.1 is already installed and up-to-date
To reinstall 2.20.1, run `brew reinstall git`
sed: 1: "/Users/mac/.zshrc": invalid command code m

**Comment by aitbahaa** [comment]
Solution is edit the file : "/Users/mac/.zshrc"
by setting the ZSH_THEME="jovial"
<img width="836" alt="screen shot 2019-01-04 at 1 59 49 am" src="https://user-images.githubusercontent.com/16513804/50669270-14dff280-0fbc-11e9-9b23-897944d81d42.png">

**Comment by zthxxx** [comment]
maybe you need gnu sed, your errors all throw by sed

`brew install gnu-sed`
