### ISSUE TITLE
Tabbing collapses previous lines

### ISSUE THREAD

**Issue by royemosby** [zthxxx/jovial#21]
When tab is hit while using this theme, it moves the command line up, removing the lines above it. If this is intentional, how is it disabled?
![tab-collaps](https://user-images.githubusercontent.com/10133316/147707352-320d7be3-327b-4d92-9f5c-ecccec1a2ad2.gif)

**Comment by zthxxx** [comment]
@royemosby thanks for use and feedback, what’s the version you used now?

> Run `echo ${JOVIAL_VERSION}` can see it

**Comment by royemosby** [comment]
2.0.0

**Comment by zthxxx** [comment]
@royemosby  This bug should be fixed in the newer version, current is v2.3.0, could you upgrade and try again?

Changelogs see: https://github.com/zthxxx/jovial/blob/master/CHANGELOG.md

Upgrade guide see: https://github.com/zthxxx/jovial#upgrade

**Comment by royemosby** [comment]
@zthxxx after running `curl -sSL https://github.com/zthxxx/jovial/raw/master/installer.sh | sudo -E bash -s $USER` it only takes me up to 2.0.2
<img width="276" alt="Screen Shot 2021-12-30 at 8 38 35 AM" src="https://user-images.githubusercontent.com/10133316/147756947-cd58c457-012f-4f1d-8a5f-d28c325f502e.png">
.

**Comment by zthxxx** [comment]
@royemosby did you restart your terminal to reload zsh?  Due to the command only download files but not reload (maybe I need add to docs...)

**Comment by royemosby** [comment]
I started a new session after completion. Even after restarting iTerm, i'm still only @ 2.0.2.

**Comment by zthxxx** [comment]
@royemosby That's weird. I tried back to 2.0.0 just now and run install command again, It exactly did upgrade to 2.3.0. 

Maybe network cache? I need more info for troubleshooting...

Additionally, for upgrade, you can copy(download) the theme file [(jovial.zsh-theme)](https://github.com/zthxxx/jovial/blob/master/jovial.zsh-theme) to override your local theme file `~/.oh-my-zsh/custom/themes/jovial.zsh-theme`

**Comment by royemosby** [comment]
I was thinking about manually copying the theme but didn't know if it'll break anything. With you saying that, I'll go ahead and do that. Thanks for the assistance!

**Comment by zthxxx** [comment]
(that's also what the install command does)

**Comment by royemosby** [comment]
Curious that did not work for me then. The move to 2.3.0 fixes my original problem.

**Comment by zthxxx** [comment]
I'm glad I solved your problem.

And would you run the curl commands below and take screenshot to me? (for troubleshooting in network)

```zsh
curl -sSL https://github.com/zthxxx/jovial/raw/master/jovial.zsh-theme | head

curl -sSL -H 'Cache-Control: no-cache' https://github.com/zthxxx/jovial/raw/master/jovial.zsh-theme | head
```

**Comment by royemosby** [comment]
<img width="934" alt="Screen Shot 2021-12-30 at 9 12 36 AM" src="https://user-images.githubusercontent.com/10133316/147759493-f7493f4a-b7e4-47d6-a97f-303cfef5c16e.png">

**Comment by zthxxx** [comment]
Thanks, that looks right. 

The upgrade-version issue maybe some other reason, but not about this issue with original problem, so I closed.
