### ISSUE TITLE
Override theme variables not working

### ISSUE THREAD

**Issue by mflilian** [zthxxx/jovial#26]
Hey everyone!
I'm trying to override the theme variables such as: [JOVIAL_SYMBOL](https://github.com/zthxxx/jovial#symbols) and [JOVIAL_PALETTE](https://github.com/zthxxx/jovial#colors) but unfortunately no success yet. 

First I did what you recommended on [symbols](https://github.com/zthxxx/jovial#symbols) section, but then I got the following error `assignment to invalid subscript range`. After doing some researches I could fix this error by adding `typeset -gA JOVIAL_SYMBOL` before any assignments of `JOVIAL_SYMBOL` to reset the type (same thing for `JOVIAL_PALETTE`).
 I'm currently not getting any error but the customization is not working, it's always getting jovial default values. 

Here's my `~/.zshrc` setting for it:

```
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="jovial"

typeset -gA JOVIAL_SYMBOL
JOVIAL_SYMBOL[git.dirty]='✘'
JOVIAL_SYMBOL[arrow]='->'
JOVIAL_SYMBOL[arrow.git-clean]='->'
JOVIAL_SYMBOL[arrow.git-dirty]='->'

typeset -gA JOVIAL_PALETTE
JOVIAL_PALETTE[host]='%F{218}'
JOVIAL_PALETTE[user]='F{224}'
JOVIAL_PALETTE[root]='%B%F{204}'
JOVIAL_PALETTE[path]='%B%F{162}%}'
JOVIAL_PALETTE[git]='%F{198}'
JOVIAL_PALETTE[venv]='%F{212}'
JOVIAL_PALETTE[time]='%F{225}'

```

I don't really know what could it be, could you help me pls?
Thanks 🎀

**Comment by zthxxx** [comment]
@mflilian  hello, thanks for use this theme~ 

All of the override should be set after "load theme", with `oh-my-zsh` that's means the line `source $ZSH/oh-my-zsh.sh` in `.zshrc`.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/15135943/201281353-300348be-ab02-489c-935c-cd03ab1c1e94.png">

**Comment by mflilian** [comment]
> @mflilian hello, thanks for use this theme~
> 
> All of the override should be set after "load theme", with `oh-my-zsh` that's means the line `source $ZSH/oh-my-zsh.sh` in `.zshrc`.
> 
> <img alt="image" width="804" src="https://user-images.githubusercontent.com/15135943/201281353-300348be-ab02-489c-935c-cd03ab1c1e94.png">

yeaaaah!!! ahhahahaha thank you so much 💟  it worked!!! I'm gonna close this issue and thanks again!
