### ISSUE TITLE
某些情况下终端的输出会带有不消失的光标

### ISSUE THREAD

**Issue by TangbohuDianPaoZhang** [zthxxx/jovial#31]
首先非常感谢作者大大的主题，非常漂亮。我是刚刚学习linux使用的学生，我在安装您的主题后在使用时发现在终端的输出末尾有时会带有一个不消失的光标，请问这个可以去掉吗？
![image](https://user-images.githubusercontent.com/93420604/236506247-a2efdda6-2d56-4be5-b048-7e8dd62f5a94.png)
我正在使用的系统是ubuntu 22.04，非常感谢！

**Comment by zthxxx** [comment]
@TangbohuDianPaoZhang  这是 zsh 特意设置，出现情况是特定的表示「command 输出最后结尾是不可见字符 `\0` 而非 `\n`」
