### ISSUE TITLE
History Show

### ISSUE THREAD

**Issue by HMDMHMDI** [zthxxx/jovial#37]
First how can i delete and remove all of your installation from mac?
and look at this problem :
<img width="772" alt="Screenshot 1402-12-15 at 11 54 39 PM" src="https://github.com/zthxxx/jovial/assets/130986160/14c7ad02-6f1e-4c90-a753-50f5655a16e7">

**Comment by zthxxx** [comment]
Sorry for some wrong experience, the problem may not relevant to _jovial_ theme, it maybe some other wrong config in your `.zshrc` or terminal, please copy and paste `~/.zshrc` into comment for more debugging info. (for shell: `pbcopy < ~/.zshrc`)

For uninstall method, that depends on how you install it:
1. for [`oh-my-zsh` or one-line command](https://github.com/zthxxx/jovial#install),
    remove jovial from `ZSH_THEME=` and `plugins=(` from `.zshrc`
2. for [antigen](https://github.com/zthxxx/jovial#use-with-antigen), remove those from `.zshrc`
    ````bash
    antigen theme zthxxx/jovial
    antigen bundle zthxxx/jovial
    antigen bundle zthxxx/zsh-history-enquirer
    ````

**Comment by zthxxx** [comment]
@HMDMHMDI  could you provide your insensitive `.zshrc` file?
